NUM_SATELLITES=18
NUM_PLANES=3
SATS_PER_PLANE=6
NUM_GATEWAYS=2
NUM_PATHS = 3
REUSE_STORED_FEASIBILITY = False
FIXED_SERVING_SATELLITE = 1
K=20
DT=30
DEMAND=350.0
HANDOVER_COST=8.0
SOURCE="z"
SATELLITES=[f"S{i}" for i in range(1,NUM_SATELLITES+1)]
GATEWAYS=[f"GW{i}" for i in range(1,NUM_GATEWAYS+1)]
TIME=list(range(K+1))
PLANE_OF={}
for p in range(NUM_PLANES):
    for s in range(SATS_PER_PLANE):
        n=p*SATS_PER_PLANE+s+1
        PLANE_OF[f"S{n}"]=p+1
